#!/usr/bin/env bash
set -euo pipefail

RUNNER="${WASMER:-wasmer}"
if ! command -v "$RUNNER" &>/dev/null; then
    echo "Wasmer not found. Please add wasmer to your PATH or set the 'WASMER' environment variable." >&2
    exit 1
fi

LIB_PATH=$(dirname "$(realpath "$1")")

ARGS=("$@")
if test "1" = "${LLVM_DEBUG:-}"; then
    ARGS+=(
        "--llvm-debug-dir" "./llvm-debug"
    )
fi

exec "${RUNNER}" run --mapdir /lib:"$LIB_PATH" --llvm "$ARGS"
