#!/usr/bin/env bash
set -euo pipefail

# Detect if we are clang or clang++
if [[ "$0" =~ "++" ]]; then
    NATIVE_COMPILER="em++"
else
    NATIVE_COMPILER="emcc"
fi

ARGS=(
    "$@"
)

# # Analyze the arguments
# # Check if we are also linking
# run_linker=true
# # We are building a shared library
# shared_library=false
# for arg in "${PASSED_ARGS[@]}"; do
#     case "$arg" in
#         -c|-S|-E)
#             run_linker=false
#             ;;
#         -shared|--shared)
#             shared_library=true
#             ;;
#     esac
# done

# if $run_linker; then
#     if $shared_library; then
#         ARGS+=(
#             -sSIDE_MODULE
#         )
#     else
#         ARGS+=(
#             -sMAIN_MODULE
#         )
#     fi
# fi

exec "$NATIVE_COMPILER" "${ARGS[@]}"