#!/usr/bin/env bash
set -euo pipefail

# Detect if we are clang or clang++
if [[ "$0" =~ "++" ]]; then
    NATIVE_COMPILER="clang++-19"
else
    NATIVE_COMPILER="clang-19"
fi

exec "$NATIVE_COMPILER" "$@"