name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: Install WASIX toolchain
        run: |
          bash scripts/setup-wasix.sh
      - name: Run tests
        run: |
          export WASIX_SYSROOT=/wasix-sysroot
          export TERM=xterm-256color
          bash test.sh | tee test.log
      - name: Summarize test results
        run: |
          summary=$(head -n 1 test.log | sed -r 's/\x1b\[[0-9;]*m//g')
          if echo "$summary" | grep -q 'failed'; then
            pass_count=$(echo "$summary" | grep -o '[0-9]\+' | head -n1)
            fail_count=$(echo "$summary" | grep -o '[0-9]\+' | sed -n '2p')
          else
            pass_count=$(echo "$summary" | grep -o '[0-9]\+' | head -n1)
            fail_count=0
          fi
          total=$((pass_count + fail_count))
          echo "$summary" > summary.txt
          {
            echo '### Test Results';
            cat summary.txt;
            echo;
            echo '| Total | Passed | Failed |';
            echo '|------:|------:|------:|';
            echo "| $total | $pass_count | $fail_count |";
          } >> "$GITHUB_STEP_SUMMARY"
          cat <<EOF > pr_comment.txt
| Total | Passed | Failed |
|------:|------:|------:|
| $total | $pass_count | $fail_count |
EOF
      - name: Post results to PR
        uses: EliLillyCo/github-actions-post-to-pr@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          post_to_pr_definition: |
            [
              {
                "message_file": "./pr_comment.txt",
                "title": "Test Results",
                "collapsible": true
              }
            ]
