name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install WASIX toolchain
        run: |
          bash scripts/setup-wasix.sh
      - name: Run tests
        run: |
          export WASIX_SYSROOT=/wasix-sysroot
          export TERM=xterm-256color
          bash test.sh | tee output.txt
      - name: Summarize test results
        run: |
          grep -E "^Test .* (passed|failed)" output.txt > summary.txt || true
          pass=$(grep -c 'passed' summary.txt || true)
          fail=$(grep -c 'failed' summary.txt || true)
          {
            echo '| Status | Count |'
            echo '| ------ | -----:|'
            echo "| Passed | ${pass:-0} |"
            echo "| Failed | ${fail:-0} |"
            echo ''
            cat summary.txt
          } > pr_comment.txt
      - name: Post to PR
        uses: EliLillyCo/github-actions-post-to-pr@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          post_to_pr_definition: |
            [
              {
                "message_file": "./pr_comment.txt",
                "title": "Test Results",
                "collapsible": true
              }
            ]
